# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jbcztgj17HJIMfxSN3nRk2UXafcCXDFl
"""

import random as rd

#10^6 trials
simlen=int(1e6)

count_scooter=0
count_car=0
count_truck=0

i=0
while i<simlen:
  i+=1
  b=rd.randint(1,12000)
  # Here 1-2000 represents scooter, 2001-6000 represents car and 
  # 6001-12000 reprsent truck
  if(b<=2000):
    count_scooter+=1
  elif(2000<b<=6000):
    count_car+=1
  else:
    count_truck+=1

pr_scooter = count_scooter/simlen 
pr_car = count_car/simlen
pr_truck = count_truck/simlen

#Given
pr_accident_when_scooter = 0.01
pr_accident_when_car = 0.03
pr_accident_when_truck = 0.15


count_scooter_and_accident=0
count_car_and_accident=0
count_truck_and_accident=0

i=0
#Checking how many of the scooter drivers had accidents
while i<count_scooter:
  i+=1
  a=rd.randint(1,100)
  if(a<=100*pr_accident_when_scooter):
    count_scooter_and_accident+=1

i=0
#Checking how many of the car drivers had accidents
while i<count_car:
  i+=1
  a=rd.randint(1,100)
  if(a<=100*pr_accident_when_car):
    count_car_and_accident+=1

i=0
#Checking how many of the truck drivers had accidents
while i<count_truck:
  i+=1
  a=rd.randint(1,100)
  if(a<=100*pr_accident_when_truck):
    count_truck_and_accident+=1

pr_accident_when_scooter = count_scooter_and_accident/count_scooter
pr_accident_when_car = count_car_and_accident/count_car
pr_accident_when_truck = count_truck_and_accident/count_truck

#Using total probability theorem to find Pr(accident)
pr_accident = pr_accident_when_scooter*pr_scooter + pr_accident_when_car*pr_car + pr_accident_when_truck*pr_truck
#Using Bayes' theorem
pr_scooter_when_accident = (pr_scooter*pr_accident_when_scooter)/pr_accident

#Theoretically calculated probability
pr_theory=1/52

#Simulation vs Theory
print(pr_scooter_when_accident,pr_theory)

