# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y0_ozKfhIkPjYyoMjoXD5n_bU-9mwU77
"""

import random as rd

# 10^6 trials
simlen = int(1e6)

count_reflexive = 0
'''

 We know that for a set of 3 elements, there are 2^9 (512) binary relations out of which 2^6 (64) are reflexive [See pdf for proof].
 Here we will generate random numbers from 1 to 2^9. If the number is less than or equal to 2^6 it represents a reflexive relation else
 it the relation is non reflexive. 

'''
i=1
while (i<=simlen):
  i+=1
  a= rd.randint(1,512)
  if(a<=64):
    count_reflexive+=1

Pr_reflexive = count_reflexive/simlen

#From theory we get
Pr_theory = 1/8

#Probability obtained by simulation vs theory
print(Pr_reflexive,Pr_theory)