# -*- coding: utf-8 -*-
"""Assignment4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GcKJ-63jghB-8Im-Qb03PPkOq5mcVSD7
"""

import random as rd

#10^6 trials
simlen=int(1e6)
count=0
i=1
while (i<=simlen):
  i+=1
  x=rd.randint(1,6)
  y=rd.randint(1,6)
  if (x==y):
    x=rd.randint(1,6)
    y=rd.randint(1,6)
    if (x==y):
      x=rd.randint(1,6)
      y=rd.randint(1,6)
      if (x!=y):
        count+=1

pr_sim = count/simlen
pr_theory = 5/216
print(pr_sim,pr_theory)